name: HookFlo Manual Trigger Test

on:
  workflow_dispatch:
    inputs:
      webhook_url:
        description: 'Target Webhook URL'
        required: true
      webhook_id:
        description: 'Header value to be sent as x-webhook-id.'
        required: true
      webhook_secret:
        description: 'Header value to be sent as x-webhook-secret.'
        required: true
      payload:
        description: 'Optional JSON payload to send'
        required: false

jobs:
  manual_hookflo_test:
    runs-on: ubuntu-latest

    steps:
      - name: Simulate Task (Fails for Testing)
        run: |
          echo "Starting manual task..."
          exit 1  # Simulate failure for testing

      - name: Notify HookFlo on Failure
        if: failure()
        uses: Hookflo/hookflo-notify-action@1.3
        with:
          webhook_url: ${{ github.event.inputs.webhook_url }}
          webhook_id: ${{ github.event.inputs.webhook_id }}
          webhook_secret: ${{ github.event.inputs.webhook_secret }}
          payload: ${{ github.event.inputs.payload }}
